[workspace]
members = [
    "packages/*",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4"
actix-cors = "0.6"
env_logger = "0.10"
rust-ini = "0.19"
colored = "2.0"
lazy_static = "1.4"
