[package]
name = "penet-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = { workspace = true }
rust-ini = { workspace = true }
lazy_static = { workspace = true }
